name: GGShield Secret Detection

on:
  pull_request:
    branches:
      - main

jobs:
  ggshield:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install GGShield
        run: |
          python -m pip install --upgrade pip
          pip install ggshield

      - name: Scan repository with GGShield
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
        run: ggshield scan pr .